import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Authenticate } from "@/lib/server/Authenticate";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie Plus",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookie = cookies().get("authToken")?.value;
  let user = null;
  if (cookie) {
    user = await Authenticate(cookie);
  }

  return (
    <html lang='en'>
      <body className={inter.className}>
        <main>
          <Navbar user={user} />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
